stages:
  - setup
  - deploy

npm-install:
  stage: setup
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
  script:
    - npm install --no-optional
  only:
    - dev
    - tags

deploy-snapshot:
  stage: deploy
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
    policy: pull
  script:
    - npm run build
    - sudo rm -fr ~by-new-crown-appointment/new-crown-appointment-front/dist
    - sudo mv dist ~by-new-crown-appointment/new-crown-appointment-front/
  only:
    - dev

package-release:
  stage: deploy
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - node_modules
    policy: pull
  script:
    - npm run build
    - releaseDir=new-crown-appointment-front-$CI_COMMIT_REF_NAME
    - mkdir $releaseDir
    - mv dist $releaseDir/
  only:
    - tags
  artifacts:
    name: "new-crown-appointment-front-${CI_COMMIT_REF_NAME}"
    expire_in: 3 days
    paths:
      - "new-crown-appointment-front-v*"
